// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: ingredients.sql

package db

import (
	"context"
	"database/sql"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (
    name, default_unit
) VALUES (
    $1, $2
) RETURNING id, name, created_at, default_unit
`

type CreateIngredientParams struct {
	Name        string        `json:"name"`
	DefaultUnit sql.NullInt32 `json:"defaultUnit"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient, arg.Name, arg.DefaultUnit)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DefaultUnit,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients
WHERE id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteIngredient, id)
	return err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, name, created_at, default_unit from ingredients
WHERE id = $1
`

func (q *Queries) GetIngredient(ctx context.Context, id int32) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DefaultUnit,
	)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, name, created_at, default_unit from ingredients
ORDER BY name
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DefaultUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchIngredients = `-- name: SearchIngredients :many
SELECT id, name, default_unit from ingredients
WHERE name LIKE $1
`

type SearchIngredientsRow struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	DefaultUnit sql.NullInt32 `json:"defaultUnit"`
}

func (q *Queries) SearchIngredients(ctx context.Context, name string) ([]SearchIngredientsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchIngredients, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchIngredientsRow
	for rows.Next() {
		var i SearchIngredientsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.DefaultUnit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients
    set name = $2,
    default_unit = $3
WHERE id = $1
RETURNING id, name, created_at, default_unit
`

type UpdateIngredientParams struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	DefaultUnit sql.NullInt32 `json:"defaultUnit"`
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, updateIngredient, arg.ID, arg.Name, arg.DefaultUnit)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.DefaultUnit,
	)
	return i, err
}
